### ISSUE TITLE
Problem with dae2scw

### ISSUE THREAD

**Issue by PhoenixFire6934** [OpegitStudio/SCW#1]
Hello,

I used the dae2scw feature and after putting the model in game I noticed the animations are not working anymore. The model just stands in T pose.

Here is the dae file if you want to take a look at it: https://we.tl/t-4TAnPhYNak

Thanks for your attention.
![Screenshot_20200903-124011_Parallel_Space_Lite](https://user-images.githubusercontent.com/63543285/92100239-35d99600-ede4-11ea-8c79-f2da8cdffa09.jpg)

**Comment by daniillnull** [comment]
Hey! Thanks for your feedback.
As I understand you edited _geo.scw_ of this character using Blender.
Sometimes when you import or export collada from Blender some NODE identifiers can be changed (usually it appends prefix with root armature name). This makes final geo.scw file incompatible with original _anim.scw_ files from game.
![изображение](https://user-images.githubusercontent.com/14278347/92132572-5f141980-ee18-11ea-8f54-add32445cbb9.png)
You can fix this by editing .dae file directly: open it in Notepad, replace "_CHARACTER__" to "" (empty string) and try to convert it.
Write here if this worked or not.

**Comment by PhoenixFire6934** [comment]
Hey, thank you so much for your help! It's working now!
![Screenshot_20200904-103909_Parallel_Space_Lite](https://user-images.githubusercontent.com/63543285/92212791-2bc69e80-ee9b-11ea-82d1-ae38864fb3ee.jpg)

**Comment by SarkisGG** [comment]
@daniillnull Do you need to erase everything with CHARACTER_, or only with R, as in the photo above?

**Comment by daniillnull** [comment]
@Croshila yep, you should replace all "CHARACTER_" to empty string. It should work fine, but if it doesn't, write here
