### ISSUE TITLE
Problem with the script

### ISSUE THREAD

**Issue by ARHCOS** [OpegitStudio/SCW#2]
I have this problem. Can you help me pls ? @daniillnull 
![2020-09-30 16_13_25-Window](https://user-images.githubusercontent.com/72146549/94696970-ebdac600-0337-11eb-9fbc-eecee0350366.png)

**Comment by daniillnull** [comment]
Hey! Looks like some part of your mesh doesn't have bound material. SCW doesn't support that, so you must bind materials.
